//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace BackEnd.DAL.Entities
{
  public class dataController_views
    {
        public long dataController_views_view { get; set; }
        public string dataController_name { get; set; }
        public string dataController_views_view_id { get; set; }
        public string dataController_views_view_type { get; set; }
        public string dataController_views_view_label { get; set; }
        public string dataController_views_view_commandId { get; set; }
        public string dataController_views_view_headerText { get; set; }
    
        public virtual dataController dataController { get; set; }
    }
}
