//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace BackEnd.DAL.Entities
{
  public partial class dataControllerCollection
    {
        public int dataControllerCollection1 { get; set; }
        public string dataControllerCollection_xmlns { get; set; }
        public string dataControllerCollection_snapshot { get; set; }
        public string dataControllerCollection_Name { get; set; }
        public string dataControllerCollection_Version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataController> dataControllers { get; set; }
    }
}
